epochs: 50
batch_size: 8
learning_rate: 0.0001
checkpoint_interval: 5

train_data_dir: "data/input/"
train_mask_dir: "data/masks/"
model_save_dir: "models/fine_tuned/InstrumentModel/"
log_dir: "training/logs/"

resume_checkpoint: null
