data_dir: "C:/Users/klab/Desktop/back-matting-new/data"
learning_rate: 0.001
num_epochs: 10
batch_size: 1

# データセットの種類を各モードに指定
dataset_type:
  train: "train"
  validation: "validation"
  test: "test"

# トレーニング用ファイルパスのリスト
train_annotation_files:
  - "C:/Users/klab/Desktop/back-matting-new/data/train/train_annotation_human.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/train/train_annotation_cello.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/train/train_annotation_piano.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/train/train_annotation_guitar.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/train/train_annotation_saxophone.csv"

# バリデーション用ファイルパスのリスト
val_annotation_files:
  - "C:/Users/klab/Desktop/back-matting-new/data/validation/validation_annotation_human.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/validation/validation_annotation_cello.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/validation/validation_annotation_piano.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/validation/validation_annotation_guitar.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/validation/validation_annotation_saxophone.csv"

# テスト用ファイルパスのリスト
test_annotation_files:
  - "C:/Users/klab/Desktop/back-matting-new/data/test/test_annotation_human.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/test/test_annotation_cello.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/test/test_annotation_piano.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/test/test_annotation_guitar.csv"
  - "C:/Users/klab/Desktop/back-matting-new/data/test/test_annotation_saxophone.csv"

# 事前学習済みモデルのパス
pretrained_model_path: "C:/Users/klab/Desktop/back-matting-new/pre-trained_Models/real-fixed-cam/netG_epoch_12.pth"

# モデルの保存先ディレクトリ
save_dir: "C:/Users/klab/Desktop/back-matting-new/fine_tuned/InstrumentModel"
