dataset_type: "train"

annotation_files:
  - "data/train/annotations_human.csv"
  - "data/train/annotations_cello.csv"
  - "data/train/annotations_piano.csv"
  - "data/train/annotations_guitar.csv"
  - "data/train/annotations_saxophone.csv"

data_dir: "data"
batch_size: 1
num_epochs: 10
learning_rate: 0.001

pretrained_model_path: "pre-trained_Models/real-fixed-cam/netG_epoch_12.pth"
save_dir: "models/"

